### ISSUE TITLE
herolte: adb/mtp accessible while SHRP is locked by a password

### ISSUE THREAD

**Issue by AntiKippi** [SHRP/bootable_recovery#13]
I've just noticed that while the password protection for the recovery itself works pretty well, ADB is enabled even when I haven't entered the password yet. This lets someone with access to a PC completly bypass the password check since anything you can do from the UI is also possible via ADB.

So please disable ADB until the password has been entered.

Not as severe as ADB but still not ideal is that the same is true for MTP. So please disable it too.

**Comment by steadfasterX** [comment]
Thx for the hint. I can confirm that this is not the wanted behavior. At the time when I've implemented that in SHRP I've ensured that neither ADB nor MTP is possible until the pass has been entered as this is crucial important (see https://github.com/SHRP/bootable_recovery/commit/3141f466a6196423a3c4ddcd640a6bf651f1a6c8).

Seems something after has broken that design. ~Will look into it asap~

does **not** affect:
- android-7.1 branch (tested)
- android-9 branch (tested)
- android-10 branch (tested)

likely affected:
- android-11 branch
- android-12 branch

regression likely introduced by (verification req): https://github.com/SHRP/bootable_recovery/commit/91bd7a7ff1ce09eb7e70f87a493a7029b65d494b#diff-e0ca1f5b9090b8052d4205bcaf58557647cf9415ce85cb207b9e24eaa352ec34R93-R96

**Comment by steadfasterX** [comment]
> I've just noticed that while the password protection for the recovery itself works pretty well, ADB is enabled even when I haven't entered the password yet. This lets someone with access to a PC completly bypass the password check since anything you can do from the UI is also possible via ADB.
> 
> So please disable ADB until the password has been entered.
> 
> Not as severe as ADB but still not ideal is that the same is true for MTP. So please disable it too.

can you test to build & report back after doing the following change:

eg. if you build on android-11 branch find the new unhandled adb line in [etc/init.rc](https://github.com/SHRP/bootable_recovery/blob/android-11.0/etc/init.rc#L113) and add `&& property:shrp.lock=0` so it looks like this:

before:
```
# Always start adbd on userdebug and eng builds
on fs && property:ro.debuggable=1
    setprop sys.usb.config adb
```

after:
```
# Always start adbd on userdebug and eng builds
on fs && property:ro.debuggable=1 && property:shrp.lock=0
    setprop sys.usb.config adb
```

also:
- tell on which SHRP branch you build
- share your device tree

**Comment by AntiKippi** [comment]
I haven't build any branch, I am using the 3.1 build from [SourceForge](https://sourceforge.net/projects/shrp/files/herolte/). My device is the Galaxy S7 "herolte" with Android 10, I am not quite sure what you mean with "device tree".

Anyways I'll have a look at building it myself and apply the fix you suggested as soon as I get to it.

**Comment by steadfasterX** [comment]
I see. then you can't do anything about that (my assumption was that you _build_ SHRP).

@morogoku , I hope you are still maintaining herolte ?! You have to adjust these lines:

1. https://github.com/SHRP-Devices/device_samsung_herolte/blob/android-9.0/recovery/root/init.recovery.usb.rc#L27
2. https://github.com/SHRP-Devices/device_samsung_herolte/blob/android-9.0/recovery/root/init.recovery.usb.rc#L33

simple add `&& property:shrp.lock=0` and the prob above should be gone

**Comment by stendro** [comment]
> before:
> 
> ```
> # Always start adbd on userdebug and eng builds
> on fs && property:ro.debuggable=1
>     setprop sys.usb.config adb
> ```

I build my own recovery, and the init.rc looks like the above example. However, when testing, after setting a lock, it seems to work as it should (no adb prior to unlocking). But there was another problem, the lock wasn't saved, I could only test by doing a 'recovery soft reboot' (clicking the circular arrow icon after setting lock).
Error:
```
export recoveryBLOCK=/dev/block/bootdevice/by-name/recovery; sh /twres/scripts/create_env.sh;
process ended with ERROR: 127
sh /twres/scripts/syncLock.sh; process ended with ERROR: 127
```

I'm using A11 branch. https://github.com/stendro/msm8996_lge_recovery/

**Comment by steadfasterX** [comment]
@stendro pls create an own issue as this is not related. besides your device tree always share the full recovery log then. thx
