### ISSUE TITLE
for twrp_rec

### ISSUE THREAD

**Issue by sam9306** [SHRP/bootable_recovery#19]
- [x] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [x] I am running the latest version of TWRP
- [x] I have read the FAQ (https://twrp.me/FAQ/)
- [x] I have searched for my issue and it does not already exist

**Device codename**: 
**TWRP version**: 

#### ADDITIONAL INFORMATION

`/tmp/recovery.log`: 
`dmesg`:

**Comment by Giovix92** [comment]
?
