### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Canary233** [SHRP/bootable_recovery#9]
After commit 8d9cfaf471458abe0c6cadb15cc00e2a12e4bae7, some erors will be reported

**Comment by steadfasterX** [comment]
> After commit [8d9cfaf](https://github.com/SHRP/bootable_recovery/commit/8d9cfaf471458abe0c6cadb15cc00e2a12e4bae7), some erors will be reported

"some errors"? What about sharing these? Might help...

**Comment by Canary233** [comment]
> > After commit [8d9cfaf](https://github.com/SHRP/bootable_recovery/commit/8d9cfaf471458abe0c6cadb15cc00e2a12e4bae7), some erors will be reported
> 
> "some errors"? What about sharing these? Might help...

The developers confirmed this issue on the tg group, I think they will fix it soon.
